# Project identification
sonar.projectKey=sonar-metrics-exporter
sonar.projectName=SonarQube Metrics Exporter
sonar.projectVersion=3.1.0
sonar.organization=domgiorda

# Server connection
sonar.host.url=https://sonarcloud.io

# Source code & tests configuration
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.source=17
sonar.sourceEncoding=UTF-8

# Code Coverage & Exclusions
sonar.coverage.exclusions=**/PrometheusExporterPlugin.java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
