global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'sonar'
    metrics_path: '/api/prometheus/metrics'
    # If SonarQube requires authentication (forceAuthentication enabled), specify credentials:
    # basic_auth:
    #   username: 'admin'
    #   password: '<your-password>'
    # OR:
    # bearer_token: '<your-sonarqube-user-token>'
    static_configs:
      - targets: ['sonar:9000']
    relabel_configs: []
