{
 "title": "Sonarqube - Project Analysis Dashboard",
 "description": "The `Sonarqube - Analysis Dashboard` dashboard presents all metrics in detail and is meant for finer-grained analytics.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Key",
    "label": "Key",
    "query": {
     "query": "label_values(sonarqube_ncloc, key)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Line of Code",
   "type": "stat",
   "description": "- Lines (lines): The number of physical lines \n- Lines of code (ncloc): The number of physical lines that contain at least one character\n- Comment lines (comment_lines): The number of lines containing comment",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_ncloc{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "gauge",
   "description": "The comment lines density = comment lines / (lines of code + comment lines) * 100",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_sqale_index{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "Quality gates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Quality Gate Status",
   "type": "stat",
   "description": "The state of the quality gate associated with your project. Possible values are ERROR and OK",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_alert_status{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Security Hostpots",
   "type": "timeseries",
   "description": "The number of classes (including nested classes, interfaces, enums, and annotations).",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sonarqube_security_hotspots{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "timeseries",
   "description": "The number of classes (including nested classes, interfaces, enums, and annotations).",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sonarqube_code_smells{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "stat",
   "description": "The number of functions. Depending on the language, a function is defined as either a function, a method, or a paragraph.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Total of Issues",
   "type": "stat",
   "description": "The total count of issues in all states.",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_violations{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Lines To Cover",
   "type": "timeseries",
   "description": "The total count of issues in the state.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 25 },
   "targets": [
    {
     "expr": "sonarqube_open_issues{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sonarqube_lines_to_cover{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sonarqube_confirmed_issues{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sonarqube_false_positive_issues{key=~\"$Key\"} ",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sonarqube_violations{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "The number of vulnerability issues.",
   "type": "stat",
   "description": "The number of vulnerability issues.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "The effort to fix all vulnerability issues",
   "type": "stat",
   "description": "The measure is stored in minutes in the DB. An 8-hour day is assumed when values are shown in days.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_security_remediation_effort{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "The number of Security Hotspots",
   "type": "stat",
   "description": "The number of Security Hotspots",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_security_hotspots_reviewed_status{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Security Rating",
   "type": "stat",
   "description": "Security Rating (security_rating)\n- A = 0 Vulnerabilities\n- B = at least 1 Minor Vulnerability\n- C = at least 1 Major Vulnerability\n- D = at least 1 Critical Vulnerability\n- E = at least 1 Blocker Vulnerability",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_security_rating{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Security review rating",
   "type": "stat",
   "description": "The security review rating is a letter grade based on the percentage of Reviewed Security Hotspots.\n- A = >= 80%\n- B = >= 70% and <80%\n- C = >= 50% and <70%\n- D = >= 30% and <50%\n- E = < 30%",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_security_review_rating{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "Duplications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Duplications",
   "type": "stat",
   "description": "- Duplicated blocks (duplicated_blocks): The number of duplicated blocks of lines.\n- Duplicated lines (duplicated_lines): The number of lines involved in duplications.\n- Duplicated files (duplicated_files): The number of files involved in duplications.",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_duplicated_lines{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sonarqube_duplicated_files{key=~\"$Key\"} ",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sonarqube_duplicated_blocks{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Duplicated Lines (%)",
   "type": "gauge",
   "description": "Duplicated lines (%) (duplicated_lines_density): duplicated_lines / (lines of code) * 100",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_duplicated_lines_density{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Coverage",
   "type": "gauge",
   "description": "Coverage = (CT + CF + LC)/(2*B + EL)\nwhere:\n- CT = conditions that have been evaluated to 'true' at least once\n- CF = conditions that have been evaluated to 'false' at least once\n- LC = covered lines = linestocover - uncovered_lines\n- B = total number of conditions\n- EL = total number of executable lines (lines_to_cover)\n",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_coverage{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "The number of lines that covered by unit test",
   "type": "stat",
   "description": "The number of lines of code that could be covered by unit tests (for example, blank lines or full comments lines are not considered as lines to cover).",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_lines_to_cover{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "The number of unit tests.",
   "type": "stat",
   "description": "The number of unit tests.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_tests{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "The frequencies of rule",
   "type": "bargauge",
   "description": "The number append of rule in scan result ",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_violations{key=~\"$Key\"}",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  { "title": "Reliability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "The total number of bug issues",
   "type": "stat",
   "description": "The total number of bug issues.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_bugs{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Reliability Rating",
   "type": "stat",
   "description": "- A = 0 Bugs\n- B = at least 1 Minor Bug\n- C = at least 1 Major Bug\n- D = at least 1 Critical Bug\n- E = at least 1 Blocker Bug",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_reliability_rating{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "The effort to fix all bug issues",
   "type": "stat",
   "description": "The measure is stored in minutes in the DB. An 8-hour day is assumed when values are shown in days.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_reliability_remediation_effort{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "Maintainability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "The total count of code smell issues",
   "type": "stat",
   "description": "The total count of code smell issues.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_code_smells{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Maintainability Rating",
   "type": "gauge",
   "description": "Formerly the SQALE rating.) The rating given to your project related to the value of your technical debt ratio. The default maintainability rating grid is:\n\n- A=0-0.05, B=0.06-0.1, C=0.11-0.20, D=0.21-0.5, E=0.51-1",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_sqale_rating{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "stat",
   "description": "A measure of effort to fix all code smells. The measure is stored in minutes in the database. An 8-hour day is assumed when values are shown in days.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_sqale_index{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "Complexity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Complexity / File",
   "type": "stat",
   "description": "Complexity / File",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_complexity{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Cognitive Complexity",
   "type": "stat",
   "description": "How hard it is to understand the code's control flow",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_cognitive_complexity{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Cyclomatic Complexity",
   "type": "stat",
   "description": "Complexity refers to cyclomatic complexity, a quantitative metric used to calculate the number of paths through the code.",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_complexity{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Project analyses events",
   "type": "table",
   "description": "Project analyses events",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "sonarqube_exporter_up{key=~\"$Key\"}",
     "legendFormat": "{{key}}"
    }
   ]
  }
 ]
}