# This workflow builds the SonarQube plugin JAR file

name: Build Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read # Allow checkout

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven' # Cache Maven dependencies

      - name: Build with Maven
        # The -B flag enables batch mode
        run: mvn -B package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonar-metrics-exporter-plugin # You can customize the artifact name
          path: target/*.jar # Assumes the JAR is in the target directory